# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 281efb291c3586e2a5bb536a536f5dbf4a93b9dcc1b85d741d5977cc762629c154749c2baf5617bcc403c729f317211c5d75acbe6b9910f806c705be398dd7ad

test:
  secret_key_base: b3fab2b689afd0159f8d3e8c7e8155f9358b2de031b414d049dc2029ef2c8e2416fbd02356cd6b9fe1e06443dcf047812ff0781ab8a6b06c2c83f706a13f3d69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
